apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-quiz.fullname" . }}
  labels:
    {{- include "simple-quiz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    {{- if .Values.liveness.enabled }}
    - port: {{ .Values.liveness.port }}
      protocol: TCP
      name: liveness
    {{- end }}

  selector:
    {{- include "simple-quiz.selectorLabels" . | nindent 4 }}
