{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-quiz.serviceAccountName" . }}
  labels:
{{ include "simple-quiz.labels" . | nindent 4 }}
{{- end -}}
